version: '2'

networks:
  default:
    name: app_local
    external: true

volumes:
  simulation:
    name: simulation
    external: true

services:
  simulation:
    container_name: simulation
    hostname: simulation
    image: simdev:0.5
    volumes:
      - 'simulation:/app'
    ports:
      - '17070-17079:17070-17079'
    build: 
      context: .
      dockerfile: Dockerfile
      tags:
        - "simdev:0.5"
