version: '2'

## mount dags, logs, plugins in /opt/bitnami/airflow/dags ...
## mount requirements.txt to /bitnami/python/requirements.txt to load connectors at startup

networks:
  default:
    name: app_local
    external: true

volumes:
  postgresql_data:
    name: postgresql_data
    driver: local

services:
  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    container_name: airflow-scheduler
    hostname: airflow-scheduler
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_FERNET_KEY=w7j+2cjw27H/kUNOmufEvNLDh+3cHWfr/YG1x1V/uJI=
      - AIRFLOW_SECRET_KEY=y/V+VPl+O+umATmXOhCbIAXWPvI8UtylJmw6GbxlLaY=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
    depends_on:
      - airflow
      - postgresql
  airflow-worker:
    container_name: airflow-worker
    hostname: airflow-worker
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_FERNET_KEY=w7j+2cjw27H/kUNOmufEvNLDh+3cHWfr/YG1x1V/uJI=
      - AIRFLOW_SECRET_KEY=y/V+VPl+O+umATmXOhCbIAXWPvI8UtylJmw6GbxlLaY=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_LOAD_EXAMPLES=no
    depends_on:
      - airflow
      - postgresql
    ports:
      - '5555:5555'
  airflow:
    container_name: airflow
    hostname: airflow
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_FERNET_KEY=w7j+2cjw27H/kUNOmufEvNLDh+3cHWfr/YG1x1V/uJI=
      - AIRFLOW_SECRET_KEY=y/V+VPl+O+umATmXOhCbIAXWPvI8UtylJmw6GbxlLaY=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_USERNAME=admin
      - AIRFLOW_PASSWORD=admin
      - AIRFLOW_EMAIL=aprueser@gmail.com
    depends_on:
      - postgresql
    ports:
      - '8080:8080'
