version: '2'

networks:
  default:
    name: app_local
    external: true

volumes:
  source_code:
    name: source_code
    external: true

services:
  juliadev:
    container_name: juliadev
    hostname: juliadev
    image: aprueser/julia:1.0
    volumes:
      - 'source_code:/root/julia_code'
    command: tail -f /dev/null
    tty: true
