version: '2'

networks:
  default:
    name: app-local
    external: true

volumes:
  redis_data:
    name: redis_data
    driver: local

services:
  redis:
    container_name: redis
    hostname: redis
    image: docker.io/bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
